on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    container: ifrazzon/jmeter:0.2.0
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run JMeter Tests
      - run: jmeter -n -t $BASEDIR/Scripts/Sandbox/Cadastro/Cadastro.jmx -l $BASEDIR/Scripts/Sandbox/Cadastro/jtlFiles/Cadastro_$FILENAME.jtl -e -o $BASEDIR/Reports/Sandbox/Cadastro/Cadastro_$FILENAME
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
