on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    container: ifrazzon/jmeter:0.2.0
    name: JMeter Test Execution
    steps:      
      - name: Checkout
      - uses: actions/checkout@v2
      - run: jmeter -n -t ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx -l result.jtl -e -o result
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result
