on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    container: ifrazzon/jmeter:0.2.0
    name: JMeter Test Execution
    steps:      
      - name: Checkout
      - uses: actions/checkout@v2
