on: [push]
jobs:
  jmeter_job:
    runs-on: ubuntu-latest
    container: ifrazzon/jmeter:0.1.0
    name: JMeter Test Execution
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run JMeter Tests
        uses: docker/ifrazzon/jmeter@0.1.0
        with:
          test-plan-path: ./TestPlans/S01_SimpleExample/S01_SimpleExample.jmx
          args: ""
          
      - name: Upload Results
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-results
          path: result.jtl
